### ISSUE TITLE
filepath case sensitivity linux/macos

### ISSUE THREAD

**Issue by sirmaxim** [unwave/material_applier#5]
I get errors that files I selected do not exist, yet I explicitly selected them.

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/matt/.config/blender/2.93/scripts/addons/atool-main/type_definer.py", line 328, in define
    image.process(db = db, no_height = no_height)
  File "/home/matt/.config/blender/2.93/scripts/addons/atool-main/image_utils.py", line 169, in process
    hash = self.hash
  File "/home/matt/.local/lib/python3.9/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/matt/.config/blender/2.93/scripts/addons/atool-main/image_utils.py", line 100, in hash
    return hashfile(self.path, hexdigest=True)
  File "/home/matt/.config/blender/2.93/scripts/addons/atool-main/imohashxx.py", line 43, in hashfile
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/run/media/matt/<redact>/megascans library/custom/surface/aluminum-scuffed/aluminum-scuffed_2k_albedo.png'


````

Under windows `Megascans Library` == `megascans library` however this is not true anywhere else.

**Comment by unwave** [comment]
Thanks. Fixed in two places. I won't force AssetData IDs to case sensitivity. I cannot test the problem. Check the last update https://github.com/unwave/atool/commit/e5391fbd380737d0e56c8c014d84cad57de1adda and tell if there still an issue.

**Comment by sirmaxim** [comment]
So it successfully constructed the group. It did not automatically connect sockets to BSDF (I'm ok with that). I mention it only because it is possibly not intended.

Uncertain effect of AssetData ID's, though it doesn't appear to affect function as of yet.

This is a [texture](https://www.sharetextures.com/textures/animals/animal_skin/) set I imported to my quixel bridge library using mixer.

```
Atool DEBUG: Getting min max for channel: RGB
Atool DEBUG: Getting channel: RGB
Atool DEBUG: Getting grayscaled.
Info: Image Animal_Skin_1_4K_AO was excluded by type 'ambient_occlusion'.
Info: The bitmap Animal_Skin_1_4K_Albedo.jpg was set as: ['albedo']
Info: The bitmap Animal_Skin_1_4K_Displacement.jpg was set as: ['displacement']
Info: The bitmap Animal_Skin_1_4K_Gloss.png was set as: ['gloss']
Info: The bitmap Animal_Skin_1_4K_Normal.jpg was set as: ['normal']
Info: The bitmap Animal_Skin_1_4K_Specular.jpg was set as: ['specular']
Info: No settings were found for the material: M_Animal_Skin_1_4K
```
