### ISSUE TITLE
Cannot install addon on Blender 3.2

### ISSUE THREAD

**Issue by Xiarno** [unwave/material_applier#6]
**Operating System:** Windows 10
**Blender version:** Blender 3.2 (Steam install)

Error code when trying to activate.
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\scripts\modules\addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "E:\3D\Addons\_scripts\addons\atool-main\__init__.py", line 93, in <module>
    modules.append(importlib.import_module('.' + stem, package = __package__))
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.2\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "E:\3D\Addons\_scripts\addons\atool-main\addon_preferences_ui.py", line 6, in <module>
    from . import bl_utils
  File "E:\3D\Addons\_scripts\addons\atool-main\bl_utils.py", line 57, in <module>
    from . import node_utils
  File "E:\3D\Addons\_scripts\addons\atool-main\node_utils.py", line 14, in <module>
    from . import type_definer
  File "E:\3D\Addons\_scripts\addons\atool-main\type_definer.py", line 15, in <module>
    from . import image_utils
  File "E:\3D\Addons\_scripts\addons\atool-main\image_utils.py", line 31, in <module>
    from . imohashxx import hashfile
ModuleNotFoundError: No module named 'atool-main.imohashxx'
```

**Comment by unwave** [comment]
Thanks. https://github.com/unwave/atool/commit/a088d781abd14ada69a8d79a926fd9b5af9a5741
